export const types = {
  SET_FILTERED_PEOPLE: 'SET_FILTERED_PEOPLE',
  SET_NO_RESULTS: 'SET_NO_RESULTS',
  SET_FILMS: 'SET_FILMS',
  SET_IS_PROCESSING: 'SET_IS_PROCESSING',
  SET_NO_RESIDENTS: 'SET_NO_RESIDENTS',
  SET_REQUEST_ERROR: 'SET_REQUEST_ERROR',
};
