/* eslint-disable import/prefer-default-export */
export const types = {
  SET_NAME: 'SET_NAME',
  SET_FILTERED_PEOPLE: 'SET_FILTERED_PEOPLE',
  SET_FILTERED_PLANETS: 'SET_FILTERED_PLANETS',
  SET_NO_RESULTS: 'SET_NO_RESULTS',
  SET_FILMS: 'SET_FILMS',
  SET_IS_PROCESSING: 'SET_IS_PROCESSING',
  SET_SELECTED_PERSON: 'SET_SELECTED_PERSON',
};
